### PR TITLE
Add lintr

### PR DESCRIPTION
**Pull request by rcannood**
* Add `lintr` to CI
* Ran `styler::style_pkg()` to fix some issues

### CODE REVIEW

**Comment by rcannood** [comment]
Hmm. `lintr` expects variable names to be snake case or symbols:

> Variable and function name style should be snake_case or symbols.

Should we switch everything inside the package to snake_case? 

Example:

```r
adata <- AnnData( ... ) # <- exception?
sce <- adata$to_sce()
seu <- adata$to_seurat()
som <- adata$to_soma()
```

**Comment by mtmorgan** [comment]
I feel (strongly) that classes should be UpperCamelCase.

**Comment by mtmorgan** [comment]
I'll address many of these as part of https://github.com/scverse/anndataR/pull/42

**Comment by rcannood** [comment]
> I feel (strongly) that classes should be UpperCamelCase.

Yeah, I agree about the classes.

Imo I agree with most of the linting, except:

* Classes should be CamelCase
* X as a variable should be allowed, given the context

I'm on the fence about `to_SingleCellExperiment` and `to_Seurat` as it mixes snake_case and CamelCase. However, `to_seurat and `to_sce` are also not very satisfying...

**Pull request merged**
