### PR TITLE
Implement basic H5AD features

### PR DESCRIPTION
**Pull request by lazappi**
Implements the basic slots for the H5AD interface.

### These features are done:

**Interface methods**
- #13 
- #16
- #14
- #15
- #19
- #17
- #18
- #26 
- #25
- #19
- Write `X`
- Write `obs`
- Write `var`
- Write `obs_names`
- Write `var_names` 

**Lower level functions** (many from @LouiseDck via #67)
- #5
- #7
- #6
- #9
- #2
- #3
- #4
- #1
- #8
- #10 
- #11

**Tests**:
- Round-trip Python anndata -> file.h5ad -> R anndataR tests have been added.

**Other**:
- Added roadmap comments

### Still to do:
- A lot of read functions are still failing or generating warnings
- Write functions are untested and are expected to be failing
- Write `layers` and write data frame
- Will add round-trip R anndataR -> file.h5ad -> Python anndata tests

### CODE REVIEW

**Comment by rcannood** [comment]
I added the roadmap comments.

@lazappi Do you intend this branch to be merged in main already?

**Comment by lazappi** [comment]
> @lazappi Do you intend this branch to be merged in main already?

I think we want to merge #68 in here first to finish the writing and then it depends how much testing you want to have (#74 will help with that).

**Comment by rcannood** [comment]
* Round-trip Python anndata -> file.h5ad -> R anndataR tests have been added.
* Will add round-trip R anndataR -> file.h5ad -> Python anndata tests
* A lot of read functions are still failing or generating warnings
* Write functions are untested and are expected to be failing

**Comment by rcannood** [comment]
Updated first message in this PR to reflect current status ;)

**Comment by rcannood** [comment]
I'm going to merge this PR into the main. A lot of functionality is still broken, but PRs #64 and #72 are sortof waiting for changes implemented in this PR.

**Pull request merged**
