### PR TITLE
Update `HDF5AnnData` to use common validation function

### PR DESCRIPTION
**Pull request by lazappi**
Related to #52 

Also modifies them to:

- Use the `self$n_obs()`/`self$n_vars()` methods
- Add an option to check the number of rows in `.validate_obsvar_dataframe()`

### CODE REVIEW

**Review by rcannood — APPROVED** [review]

**Review by rcannood — CHANGES_REQUESTED** [review]
Please fix linting issues ;)

    Warning: file=R/AbstractAnnData.R,line=184,col=71,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/AbstractAnnData.R,line=187,col=1,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/AbstractAnnData.R,line=191,col=1,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/AbstractAnnData.R,line=193,col=23,[function_left_parentheses_linter] Remove spaces before the left parenthesis in a function call.
    Warning: file=R/AbstractAnnData.R,line=197,col=1,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/AbstractAnnData.R,line=202,col=1,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/AbstractAnnData.R,line=219,col=1,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/AbstractAnnData.R,line=220,col=20,[function_left_parentheses_linter] Remove spaces before the left parenthesis in a function call.
    Warning: file=R/AbstractAnnData.R,line=224,col=1,[trailing_whitespace_linter] Trailing whitespace is superfluous.
    Warning: file=R/HDF5AnnData.R,line=58,col=66,[trailing_whitespace_linter] Trailing whitespace is superfluous.

**Comment by lazappi** [comment]
> Please fix linting issues ;)

Done. I blame RStudio, for some reason it isn't stripping whitespace properly and **{lintr}** doesn't like the snippet for `switch()`.

**Review by rcannood — CHANGES_REQUESTED** [review]
Please fix linting issues 😊

```
Warning: file=R/AbstractAnnData.R,line=221,col=20,[function_left_parentheses_linter] Remove spaces before the left parenthesis in a function call.
Warning: file=R/HDF5AnnData.R,line=58,col=66,[trailing_whitespace_linter] Trailing whitespace is superfluous.

**Comment by rcannood** [comment]
( I think you can use [`styler::style_pkg()`](https://styler.r-lib.org/reference/style_pkg.html) to automatically solve most of the issues.)

**Review by rcannood — APPROVED** [review]

**Pull request merged**
